# Generated by Django 5.0 on 2024-06-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpf', models.CharField(blank=True, max_length=15, null=True)),
                ('nome', models.CharField(blank=True, max_length=250, null=True)),
                ('sexo', models.CharField(blank=True, max_length=5, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=10, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('uf_nascimento', models.CharField(blank=True, max_length=5, null=True)),
                ('nome_pai', models.CharField(blank=True, max_length=250, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=250, null=True)),
                ('ajuizado', models.IntegerField(blank=True, null=True)),
                ('central', models.IntegerField(blank=True, null=True)),
                ('acordo_limpanomes', models.IntegerField(blank=True, null=True)),
                ('acordo_saiuacordo', models.IntegerField(blank=True, null=True)),
                ('enderecos', models.TextField(blank=True, null=True)),
                ('emails', models.TextField(blank=True, null=True)),
                ('telefones', models.TextField(blank=True, null=True)),
                ('contratos', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
