# Generated by Django 5.0 on 2025-01-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('cpf', models.TextField()),
                ('contrato', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contrato', models.TextField()),
                ('cpf', models.CharField(max_length=15)),
                ('saldo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=250, null=True)),
                ('cpf', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('telefone', models.TextField(blank=True, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
