# Generated by Django 5.0 on 2025-01-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0002_contatos_contrato_pessoas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='empresa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
