# Generated by Django 5.0 on 2025-01-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0003_pessoas_empresa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contrato',
            new_name='Contratos',
        ),
    ]
