# Generated by Django 5.0 on 2025-01-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0004_rename_contrato_contratos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoas',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
