# Generated by Django 5.0 on 2025-01-29 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0004_rename_contrato_contratos'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatos',
            name='campos_perso',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='campos_perso',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='campos_perso',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='data_nascimento',
            field=models.DateField(),
        ),
    ]
