# Generated by Django 5.0 on 2025-01-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0005_alter_pessoas_data_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoas',
            name='data_nascimento',
        ),
    ]
