# Generated by Django 5.0 on 2025-01-30 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0005_contatos_campos_perso_contratos_campos_perso_and_more'),
        ('terceirizada', '0006_remove_pessoas_data_nascimento'),
    ]

    operations = [
    ]
