# Generated by Django 5.0 on 2025-01-30 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0007_merge_20250130_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoas',
            old_name='nome',
            new_name='nome_completo',
        ),
    ]
