# Generated by Django 5.0 on 2025-02-03 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0008_rename_nome_pessoas_nome_completo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoas',
            name='data_nascimento',
        ),
        migrations.AddField(
            model_name='contratos',
            name='empresa',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='email',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='telefone',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
