# Generated by Django 5.0 on 2025-02-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0009_remove_pessoas_data_nascimento_contratos_empresa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segmentacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('query', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pessoas',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='endereco',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='estado_civil',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='sexo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
