# Generated by Django 5.0 on 2025-02-05 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terceirizada', '0010_segmentacao_pessoas_data_nascimento_pessoas_endereco_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contatos',
        ),
        migrations.DeleteModel(
            name='Contratos',
        ),
        migrations.DeleteModel(
            name='Pessoas',
        ),
        migrations.DeleteModel(
            name='Segmentacao',
        ),
    ]
