# Generated by Django 5.0 on 2024-04-22 20:14

import core.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acordo_id', models.CharField(default=core.models.gerar_acordo_id, max_length=7)),
                ('cpf', models.CharField(max_length=20)),
                ('contratos', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(max_length=20)),
                ('num_parcelas_acordo', models.IntegerField()),
                ('id_resolvecontas', models.IntegerField(blank=True, null=True)),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dia_vencimento_primeira_parcela', models.DateField()),
                ('dia_vencimento_proxima_parcela', models.DateField()),
                ('valor_do_acordo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcelas', models.JSONField(default=list)),
                ('status', models.CharField(default='Simulação', max_length=10)),
                ('data_aceite', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Arquivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_inclusao', models.FileField(blank=True, null=True, upload_to=core.models.path_and_rename)),
                ('documento_exclusao', models.FileField(blank=True, null=True, upload_to=core.models.path_and_rename)),
                ('documento_inclusao_devedor', models.FileField(blank=True, null=True, upload_to=core.models.path_and_rename)),
                ('documento_exclusao_devedor', models.FileField(blank=True, null=True, upload_to=core.models.path_and_rename)),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('data_processamento', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='Concluído', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_modificacao', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
