# Generated by Django 5.0 on 2024-04-23 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_ativo_grupo_ativo'),
        ('core', '0002_acordo_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='acordo',
            name='grupo_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grupo_acordo', to='accounts.grupo'),
            preserve_default=False,
        ),
    ]
