# Generated by Django 5.0 on 2024-04-23 13:33

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_acordo_grupo_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acordo',
            name='acordo_id',
            field=models.CharField(blank=True, default=core.models.gerar_acordo_id, max_length=7, null=True),
        ),
    ]
