# Generated by Django 5.0 on 2024-04-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_acordo_acordo_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acordo',
            name='parcelas',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
