# Generated by Django 5.0 on 2024-04-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_acordo_parcelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acordo',
            name='dia_vencimento_primeira_parcela',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='acordo',
            name='dia_vencimento_proxima_parcela',
            field=models.DateField(blank=True, null=True),
        ),
    ]
