# Generated by Django 5.0 on 2024-04-25 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_ativo_grupo_ativo'),
        ('core', '0006_alter_acordo_dia_vencimento_primeira_parcela_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acordo',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='acordo',
            name='grupo_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupo_acordo', to='accounts.grupo'),
        ),
    ]
