# Generated by Django 5.0 on 2024-04-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_acordo_desconto_alter_acordo_grupo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='acordo',
            name='carteira_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acordo',
            name='data_criacao',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='acordo',
            name='maior_desconto_valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acordo',
            name='max_parcelas',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='acordo',
            name='menor_desconto_valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='acordo',
            name='min_parcelas',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='acordo',
            name='valor_pendente',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='acordo',
            name='parcelas',
            field=models.JSONField(default=list),
        ),
    ]
