# Generated by Django 5.0 on 2024-04-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_acordo_carteira_id_acordo_data_criacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acordo',
            name='parcelas',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
