# Generated by Django 5.0 on 2024-04-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_acordo_parcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='acordo',
            name='contrato_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acordo',
            name='num_parcelas_acordo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
