# Generated by Django 5.0 on 2024-05-02 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_acordo_contrato_id_alter_acordo_num_parcelas_acordo'),
    ]

    operations = [
        migrations.AddField(
            model_name='acordo',
            name='contrato_num',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
