# Generated by Django 5.0 on 2024-05-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_acordo_contrato_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='acordo',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
