# Generated by Django 5.0 on 2024-07-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_acordo_usuario_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='acordo',
            name='nome_pessoa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
