# Generated by Django 5.0 on 2024-07-30 22:52

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_acordo_nome_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='acordo',
            name='data_expiracao_proposta',
            field=models.DateTimeField(default=core.models.tomorrow),
        ),
    ]
