# Generated by Django 5.0 on 2024-07-31 12:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_acordo_data_expiracao_proposta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acordo',
            name='data_expiracao_proposta',
            field=models.DateTimeField(blank=True, default=core.models.tomorrow, null=True),
        ),
    ]
