# Generated by Django 5.0 on 2024-08-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_acordo_data_expiracao_proposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='acordo',
            name='status_proposta',
            field=models.CharField(default='Aberta', max_length=50),
        ),
        migrations.AddField(
            model_name='acordo',
            name='url_proposta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
