# Generated by Django 5.0 on 2024-11-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_acordo_status_proposta_acordo_url_proposta'),
    ]

    operations = [
        migrations.AddField(
            model_name='acordo',
            name='closer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='acordo',
            name='sdr_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
