# Generated by Django 5.0 on 2024-11-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_acordo_closer_id_acordo_sdr_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='acordo',
            name='mensagens',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
