# Generated by Django 5.0 on 2025-04-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_acordo_mensagens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carteira',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='carteira',
            name='data_modificacao',
        ),
        migrations.AddField(
            model_name='carteira',
            name='caracteristicas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carteira',
            name='descricao_cessao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carteira',
            name='descricao_divida',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carteira',
            name='descricao_produto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carteira',
            name='empresa_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carteira',
            name='fontes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='nome',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
