# Generated by Django 5.0 on 2025-04-07 23:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_carteira_data_criacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carteira',
            name='caracteristicas',
        ),
        migrations.RemoveField(
            model_name='carteira',
            name='descricao_cessao',
        ),
        migrations.RemoveField(
            model_name='carteira',
            name='descricao_divida',
        ),
        migrations.RemoveField(
            model_name='carteira',
            name='descricao_produto',
        ),
        migrations.RemoveField(
            model_name='carteira',
            name='empresa_id',
        ),
        migrations.RemoveField(
            model_name='carteira',
            name='fontes',
        ),
        migrations.AddField(
            model_name='carteira',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='carteira',
            name='data_modificacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='carteira',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
