# Generated by Django 5.0 on 2024-08-21 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MassasFalidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=20, null=True)),
                ('nome', models.CharField(blank=True, max_length=250, null=True)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('credito_classe1_2010_faixa', models.CharField(blank=True, max_length=100, null=True)),
                ('credito_classe1_2010_valor', models.CharField(blank=True, max_length=100, null=True)),
                ('credito_classe3_2010_faixa', models.CharField(blank=True, max_length=100, null=True)),
                ('credito_classe3_2010_valor', models.CharField(blank=True, max_length=100, null=True)),
                ('credito_2010_total', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa_2010', models.CharField(blank=True, max_length=100, null=True)),
                ('reserva_classe1_2010_faixa', models.CharField(blank=True, max_length=100, null=True)),
                ('reserva_classe1_2010_valor', models.CharField(blank=True, max_length=100, null=True)),
                ('reserva_classe3_2010_faixa', models.CharField(blank=True, max_length=100, null=True)),
                ('reserva_classe3_2010_valor', models.CharField(blank=True, max_length=100, null=True)),
                ('reserva_2010_total', models.CharField(blank=True, max_length=100, null=True)),
                ('credito_classe1_2024_faixa', models.CharField(blank=True, max_length=100, null=True)),
                ('credito_classe1_2024_valor', models.CharField(blank=True, max_length=100, null=True)),
                ('credito_classe3_2024_faixa', models.CharField(blank=True, max_length=100, null=True)),
                ('credito_classe3_2024_valor', models.CharField(blank=True, max_length=100, null=True)),
                ('credito_2024_total', models.CharField(blank=True, max_length=100, null=True)),
                ('empresa_2024', models.CharField(blank=True, max_length=100, null=True)),
                ('reserva_classe1_2024_faixa', models.CharField(blank=True, max_length=100, null=True)),
                ('reserva_classe1_2024_valor', models.CharField(blank=True, max_length=100, null=True)),
                ('reserva_classe3_2024_faixa', models.CharField(blank=True, max_length=100, null=True)),
                ('reserva_classe3_2024_valor', models.CharField(blank=True, max_length=100, null=True)),
                ('reserva_2024_total', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
