# Generated by Django 5.0 on 2024-04-23 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='grupo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='grupo_usuario', to='accounts.grupo'),
            preserve_default=False,
        ),
    ]
