# Generated by Django 5.0 on 2024-04-26 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_ativo_grupo_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupo_usuario', to='accounts.grupo'),
        ),
    ]
