# Generated by Django 5.0 on 2024-06-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='id_central',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
