# Generated by Django 5.0 on 2024-08-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_grupo_cnpj_grupo_email_grupo_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
