# Generated by Django 5.0 on 2024-08-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_customuser_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
    ]
