# Generated by Django 5.0 on 2025-02-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_grupo_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='tipo',
            field=models.CharField(blank=True, choices=[('adm', 'adm'), ('business', 'business'), ('parceiro', 'parceiro')], default=False, max_length=50, null=True),
        ),
    ]
