# Generated by Django 5.1.4 on 2025-01-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_grupo_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('razao_social', models.CharField(max_length=255)),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('ativo', models.BooleanField(default=True)),
                ('sftp_host', models.CharField(blank=True, max_length=255, null=True)),
                ('sftp_port', models.PositiveIntegerField(default=22)),
                ('sftp_user', models.CharField(blank=True, max_length=255, null=True)),
                ('sftp_password', models.CharField(blank=True, max_length=255, null=True)),
                ('sftp_key', models.FileField(blank=True, null=True, upload_to='sftp_keys/')),
            ],
        ),
    ]
