# Generated by Django 5.1.4 on 2025-01-09 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='sftp_key',
            field=models.FileField(blank=True, null=True, upload_to='sftp_keys'),
        ),
    ]
