# Generated by Django 5.1.4 on 2025-01-10 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_empresa_avatar_alter_empresa_sftp_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_usuario', to='accounts.empresa'),
        ),
    ]
