# Generated by Django 5.1.4 on 2025-01-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_customuser_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='sftp_port',
            field=models.PositiveIntegerField(default=8022),
        ),
    ]
