# Generated by Django 5.0 on 2025-02-04 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_grupo_tipo'),
        ('accounts', '0013_alter_empresa_sftp_port'),
    ]

    operations = [
    ]
