# Generated by Django 5.0 on 2025-02-04 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_merge_0010_grupo_tipo_0013_alter_empresa_sftp_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='empresa',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
