# Generated by Django 5.0 on 2025-04-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_customuser_empresa_delete_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='sftp_host',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='sftp_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='sftp_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grupo',
            name='sftp_user',
            field=models.TextField(blank=True, null=True),
        ),
    ]
