# Generated by Django 5.0 on 2025-04-01 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_grupo_sftp_host_grupo_sftp_key_grupo_sftp_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='sftp_pass',
            field=models.TextField(blank=True, null=True),
        ),
    ]
