# Generated by Django 5.0 on 2024-09-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PessoasTerceirizadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_resolvecontas', models.IntegerField(blank=True, null=True)),
                ('id_piperun', models.IntegerField(blank=True, null=True)),
                ('cpf', models.CharField(blank=True, max_length=15, null=True)),
                ('nome', models.CharField(blank=True, max_length=250, null=True)),
                ('sexo', models.CharField(blank=True, max_length=5, null=True)),
                ('data_nascimento', models.DateTimeField(blank=True, null=True)),
                ('estado_civil', models.CharField(blank=True, max_length=10, null=True)),
                ('uf_nascimento', models.CharField(blank=True, max_length=5, null=True)),
                ('nome_pai', models.CharField(blank=True, max_length=250, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=250, null=True)),
                ('pefin', models.IntegerField(blank=True, null=True)),
                ('terceirizada', models.IntegerField(blank=True, null=True)),
                ('enderecos', models.TextField(blank=True, null=True)),
                ('emails', models.TextField(blank=True, null=True)),
                ('telefones', models.TextField(blank=True, null=True)),
                ('contratos', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
