# Generated by Django 5.0 on 2025-02-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contrato', models.CharField(blank=True, max_length=50, null=True)),
                ('cpf', models.CharField(blank=True, max_length=15, null=True)),
                ('saldo_a_pagar', models.TextField(blank=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, null=True)),
                ('empresa_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('cpf', models.CharField(blank=True, max_length=15, null=True)),
                ('empresa_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=250, null=True)),
                ('cpf', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.TextField(blank=True, default='[]', null=True)),
                ('telefone', models.TextField(blank=True, default='[]', null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('nome_pai', models.CharField(blank=True, max_length=250, null=True)),
                ('nome_mae', models.CharField(blank=True, max_length=250, null=True)),
                ('sexo', models.TextField(blank=True, null=True)),
                ('estado_civil', models.TextField(blank=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, default=dict, null=True)),
                ('empresa_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Segmentacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('query', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateField(blank=True, null=True)),
                ('empresa_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Telefones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('cpf', models.CharField(blank=True, max_length=15, null=True)),
                ('empresa_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
