# Generated by Django 5.0 on 2025-02-05 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_criacao', models.DateField(blank=True, null=True)),
                ('empresa_id', models.IntegerField(blank=True, null=True)),
                ('custom_columns', models.JSONField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=250, null=True)),
                ('file_path', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='contratos',
            name='custom_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pessoas',
            name='custom_fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
