# Generated by Django 5.0 on 2025-02-06 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_importacao_alter_contratos_custom_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacao',
            name='list_erros',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importacao',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='importacao',
            name='tipo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='importacao',
            name='total_atualizar',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importacao',
            name='total_erros',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='importacao',
            name='total_registros',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
