# Generated by Django 5.0 on 2025-02-06 22:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_importacao_list_erros_importacao_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importacao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
