# Generated by Django 5.0 on 2025-02-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_importacao_usuario_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacao',
            name='usuario_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
