# Generated by Django 5.0 on 2025-02-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_remove_importacao_usuario_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CamposImportacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=150, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('default', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
                ('data_type', models.CharField(blank=True, max_length=150, null=True)),
                ('empresa_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
