# Generated by Django 5.0 on 2025-02-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_camposimportacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='camposimportacao',
            name='import_type',
            field=models.CharField(blank=True, choices=[('pessoas', 'pessoas'), ('contratos', 'contratos')], default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='camposimportacao',
            name='data_type',
            field=models.CharField(blank=True, choices=[('char', 'char'), ('text', 'text'), ('float', 'float'), ('bool', 'bool'), ('date', 'date'), ('int', 'int'), ('list', 'list')], default=False, max_length=50, null=True),
        ),
    ]
