# Generated by Django 5.0 on 2025-02-08 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_camposimportacao_import_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='camposimportacao',
            name='label',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
