# Generated by Django 5.0 on 2025-02-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_camposimportacao_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camposimportacao',
            old_name='descricao',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='camposimportacao',
            old_name='titulo',
            new_name='name',
        ),
    ]
