# Generated by Django 5.0 on 2025-02-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_rename_descricao_camposimportacao_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importacao',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
