# Generated by Django 5.0 on 2025-02-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_importacao_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camposimportacao',
            old_name='default',
            new_name='default_col',
        ),
    ]
