# Generated by Django 5.0 on 2025-02-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_rename_default_camposimportacao_default_col'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmentacao',
            name='query',
        ),
        migrations.AddField(
            model_name='segmentacao',
            name='conditions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='segmentacao',
            name='query_path',
            field=models.FilePathField(blank=True, null=True),
        ),
    ]
