# Generated by Django 5.0 on 2025-02-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_remove_segmentacao_query_segmentacao_conditions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentacao',
            name='update_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
