# Generated by Django 5.0 on 2025-02-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_segmentacao_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='camposimportacao',
            name='slug_db',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
