# Generated by Django 5.0 on 2025-02-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_camposimportacao_slug_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segmentacao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='segmentacao',
            name='update_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
