# Generated by Django 5.0 on 2025-02-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_alter_segmentacao_data_criacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acoes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('action_type', models.CharField(blank=True, choices=[('sms', 'sms'), ('whatsapp', 'whatsapp'), ('leva', 'leva')], default=False, max_length=50, null=True)),
                ('empresa_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
