# Generated by Django 5.0 on 2025-02-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_acoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fluxos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('grupos', models.TextField(blank=True, null=True)),
                ('id_acao', models.IntegerField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True, null=True)),
                ('data_inicio', models.DateTimeField(auto_now_add=True, null=True)),
                ('periodicidade', models.IntegerField(blank=True, null=True)),
                ('unidade_tempo', models.CharField(blank=True, max_length=250, null=True)),
                ('termino', models.CharField(blank=True, max_length=250, null=True)),
                ('qtd_ocorrencias', models.IntegerField(blank=True, null=True)),
                ('data_termino', models.DateTimeField(auto_now_add=True, null=True)),
                ('ativo', models.BooleanField(default=False)),
                ('empresa_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
