# Generated by Django 5.0 on 2025-03-16 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_fluxos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDeContatos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('contatos', models.JSONField(blank=True, null=True)),
                ('empresa_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='fluxos',
            name='id_acao',
        ),
        migrations.AddField(
            model_name='fluxos',
            name='acao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acao_fluxo', to='business.acoes'),
        ),
    ]
