# Generated by Django 5.0 on 2025-04-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0020_listadecontatos_remove_fluxos_id_acao_fluxos_acao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=250, null=True)),
                ('descricao_produto', models.TextField(blank=True, null=True)),
                ('caracteristicas', models.TextField(blank=True, null=True)),
                ('descricao_cessao', models.TextField(blank=True, null=True)),
                ('descricao_divida', models.TextField(blank=True, null=True)),
                ('fontes', models.TextField(blank=True, null=True)),
                ('empresa_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
