# Generated by Django 5.0 on 2025-04-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0031_carteira'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='bairroComercial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='bairroResidencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='cepResidencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='cidadeComercial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='cidadeResidencia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='complementoComercial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='compĺementoResidencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='dataEmissaoRg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='enderecoComercial',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='enderecoResidencia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='numeroComercial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='numeroResidencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='orgaoEmissorRg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='orgaoEmissorRgUf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='ufComercial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='ufResidencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
