# Generated by Django 5.0 on 2025-04-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0032_pessoas_bairrocomercial_pessoas_bairroresidencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoas',
            name='carteira_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pessoas',
            name='import_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
