# Generated by Django 5.0 on 2025-04-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0033_pessoas_carteira_id_pessoas_import_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='data_contratacao',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='data_vencimento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='numero_parcelas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='parcelas_nao_pagas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='parcelas_pagas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='proximo_vencimento_aberto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='taxa_financeira',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='valor_contratado',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contratos',
            name='valor_parcela',
            field=models.FloatField(blank=True, null=True),
        )
    ]
